#!/bin/sh
apt-get update

echo "installing python and pip"
apt-get install python3
apt-get install python3-pip
echo "finished installing python and pip

echo "installing neovim"
apt-get install neovim
echo "installed neovim"
echo "installing junegunn plugin manager"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "installed junegunn plugin manager"

echo "installing xkeysnail"
pip3 install xkeysnail
echo "installed xkeysnail"
echo "setting sudo permissions for xkeysnail"
sudo groupadd -f uinput
sudo gpasswd -a $USER uinput
cat <<EOF | sudo tee /etc/udev/rules.d/70-xkeysnail.rules KERNEL=="uinput", GROUP="uinput", MODE="0660", OPTIONS+="static_node=uinput" KERNEL=="event[0-9]*", GROUP="uinput", MODE="0660" EOF
echo "finished setting sudo permissions for xkeysnail"
