#!/bin/sh
apt-get update

echo "installing regular packages (python pip neovim)"
apt-get install python3 python3-pip neovim curl -y
echo "finished installing packages"

echo "installing junegunn plugin manager"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "installed junegunn plugin manager"

echo "installing xkeysnail"
pip3 install xkeysnail
echo "xkeysnail installed"
echo "setting/giving sudo permissions for xkeysnail"
groupadd -f uinput
gpasswd -a $USER uinput
echo "giving xkeysnail permission"
cat <<EOF | sudo tee /etc/udev/rules.d/70-xkeysnail.rules
KERNEL=="uinput", GROUP="uinput", MODE="0660", OPTIONS+="static_node=uinput"
KERNEL=="event[0-9]*", GROUP="uinput", MODE="0660" 
EOF

echo "finished setting sudo permissions for xkeysnail"
